#!/bin/bash
 
sudo apt-get install -y python3-dev build-essential
sudo apt-get install -y  python3-dev
sudo apt-get install -y libevent-dev
sudo apt install -y python3-pip 

pip3 install -r KEEPCLICKLOCAL/requirements.txt
streamlit run KEEPCLICKLOCAL/KEEPCLICK.py --server.enableXsrfProtection=false   
